serie_index:
    path:     /
    defaults: { _controller: "AcmeProductBundle:Serie:index" }
    methods:  GET

serie_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeProductBundle:Serie:show" }
    methods:  GET

serie_new:
    path:     /new
    defaults: { _controller: "AcmeProductBundle:Serie:new" }
    methods:  [GET, POST]

serie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeProductBundle:Serie:edit" }
    methods:  [GET, POST]

serie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeProductBundle:Serie:delete" }
    methods:  DELETE
