acme_product_product:
    resource: "@AcmeProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

acme_product_serie:
    resource: "@AcmeProductBundle/Resources/config/routing/serie.yml"
    prefix:   /serie
