purchaseorder_index:
    path:     /
    defaults: { _controller: "AcmeOrderBundle:PurchaseOrder:index" }
    methods:  GET

purchaseorder_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeOrderBundle:PurchaseOrder:show" }
    methods:  GET

purchaseorder_new:
    path:     /new
    defaults: { _controller: "AcmeOrderBundle:PurchaseOrder:new" }
    methods:  [GET, POST]

purchaseorder_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeOrderBundle:PurchaseOrder:edit" }
    methods:  [GET, POST]

purchaseorder_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeOrderBundle:PurchaseOrder:delete" }
    methods:  DELETE
