cart_index:
    path:     /
    defaults: { _controller: "AcmeCartBundle:Cart:index" }
    methods:  GET

cart_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeCartBundle:Cart:show" }
    methods:  GET

cart_new:
    path:     /new
    defaults: { _controller: "AcmeCartBundle:Cart:new" }
    methods:  [GET, POST]

cart_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeCartBundle:Cart:edit" }
    methods:  [GET, POST]

cart_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeCartBundle:Cart:delete" }
    methods:  DELETE
