# This file is part of the Web package.

acme_frontend:
    resource: @AcmeWebBundle/Resources/config/routing/frontend/main.yml

acme_backend:
    resource: @AcmeWebBundle/Resources/config/routing/backend/main.yml
    prefix: /admin

acme_myaccount:
    resource: @AcmeWebBundle/Resources/config/routing/myaccount/main.yml
    prefix: /myaccount

acme_webbundle_cpanel:
    resource: @AcmeWebBundle/Resources/config/routing/cpanel/main.yml
    prefix: /cpanel

# acme_partial:
#     resource: @AcmeWebBundle/Resources/config/routing/product/main.yml
#     prefix: /product

# acme_partial:
#     resource: @AcmeWebBundle/Resources/config/routing/partial/main.yml
#     prefix: /_partial


